name: exception_catcher
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^1.0.1
  mailer: ^5.3.0
  package_info_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

